# Generated by Django 3.2.19 on 2023-05-31 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230531_1012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='skill',
        ),
    ]
