# Generated by Django 3.2.19 on 2023-05-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
    ]
